### ISSUE TITLE
how to stop request when file larger then 2MB

### ISSUE THREAD

**Issue by eflylab** [zemirco/express-upload-progress#2]
app.use(express.bodyParser({ 
    keepExtensions: true, 
    uploadDir: __dirname + '/tmp',
    limit: '2mb'
  }));

 this code , customer can recive  "entity too large" when upload a file larger then 2MB,

but when i upload a  larger file,example 1GB, I  must wait a long time for server response.

any method can stop customer upload ,
and server response a friendly error message?

**Comment by zemirco** [comment]
Express automatically checks the file size when uploading. Somehow Heroku doesn't return the proper error code `413 Request Entity Too Large`. The code works fine on `localhost`.

I added the `onerror` handler that catches errors during file upload. Inside this handler you can specify your error message. At the moment it says

> An error occurred while submitting the form. Maybe your file is too big

Unfortunately you can't be sure about the reason for the error as Heroku doesn't provide any details.
